#JekyLL部署位置
destination: docs
#作者信息
author:
  name: CH053N
  description: i'm Waiting 4 U ~
#默认URL路径
permalink: /:year/:month/:day/:title
#默认URL
url: http://cho159.github.io
baseurl: /docs
# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed