#JekyLL部署位置
destination: docs
#作者信息
author:
  name: CH053N
  description: C'est la vie.
#默认URL路径
permalink: /:year/:month/:day/:title
#默认URL
url: http://cho159.github.io
baseurl: 
#Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
#markdown解析
markdown: kramdown
highlighter: rouge